version: 1.14.1.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: false
environment:
  lsltag: 1.13.0-b13
  lslversion: 1.13.0
  LSLDIST_URL: "https://github.com/sccn/liblsl/releases/download"
  CMakeArgs: ""
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      QTCOMPILER: msvc2017_64
      QTVER: 5.13
install:
- cmd: appveyor DownloadFile %LSLDIST_URL%/%lsltag%/liblsl-%lslversion%-Win64.7z -FileName liblsl_x64.7z
- cmd: 7z x liblsl_x64.7z -oLSL
build_script:
- cmd: cmake -S . -B build -DQt5_DIR=C:/Qt/%QTVER%/%QTCOMPILER%/lib/cmake/Qt5 -Dlsl_DIR=LSL/share/LSL %CMakeArgs%
- cd build
- cmake --build . --config Release --target install
- cpack -C Release
artifacts:
- path: 'build/*.7z'
deploy:
  provider: GitHub
  auth_token: 
    secure: b6713813f023eddaf234c1dbb095771567435c0a
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true