version: 1.14.1.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
environment:
  lsltag: 1.13.0-b13
  lslversion: 1.13.0
  LSLDIST_URL: "https://github.com/sccn/liblsl/releases/download"
  CMakeArgs: ""
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      QTCOMPILER: msvc2017_64
      QTVER: 5.13
install:
- cmd: appveyor DownloadFile %LSLDIST_URL%/%lsltag%/liblsl-%lslversion%-Win64.7z -FileName liblsl_x64.7z
- cmd: 7z x liblsl_x64.7z -oLSL
build_script:
- cmd: cmake -S . -B build -DQt5_DIR=C:/Qt/%QTVER%/%QTCOMPILER%/lib/cmake/Qt5 -Dlsl_DIR=LSL/share/LSL %CMakeArgs%
- cd build
- cmake --build . --config Release --target install
- cpack -C Release
artifacts:
- path: 'build/*.7z'
deploy:
  provider: GitHub
  appveyor_repo_tag: true
  auth_token: fbd798bc62c49759b4c3bbfa46cc9caea4f1dc7c
  force_update: true
  draft: false
  prerelease: false
  tags: true
  tag: $(APPVEYOR_REPO_TAG_NAME)
 